// Generated by CoffeeScript 1.8.0
(function() {
  (function($) {
    var getCliente, getClientes;
    $("#cod-cliente").on("blur", function() {
      return getCliente($(this));
    });
    '$( window ).on( "beforeunload", () ->\n	return "Todos los datos actuales se perderan si continúa." \n)';
    $("#search-clientes").on("click", function() {
      return getClientes();
    });
    $("body").on("click", ".list-cli-row", function() {
      $("#cod-cliente").val($(this).data("cid"));
      $("#modal-clientes").modal('hide');
      return $("#cod-cliente").blur();
    });
    getCliente = function(elm) {
      var data, val;
      val = elm.val();
      data = {
        'accion': "obtener-cliente",
        'data': {}
      };
      data.data['cliente-id'] = val;
      if (val !== '') {
        $.ajax({
          beforeSend: function(xhr, settings) {
            return null;
          },
          complete: function(xhr, status) {
            return null;
          },
          data: '&json=' + JSON.stringify(data),
          success: function(data, status, xhr) {
            var obj;
            obj = $.parseJSON(data);
            if (obj.estado === "exito") {
              return $("#datos-cliente").html("" + obj.data.nombre + "<br><small>" + obj.data.direccion + "</small>");
            }
          },
          type: 'POST',
          url: "ajax.php"
        });
        return null;
      }
    };
    return getClientes = function() {
      var data;
      data = {
        'accion': "obtener-clientes",
        'data': {}
      };
      $.ajax({
        beforeSend: function(xhr, settings) {
          return null;
        },
        complete: function(xhr, status) {
          return null;
        },
        data: '&json=' + JSON.stringify(data),
        success: function(data, status, xhr) {
          var obj;
          obj = $.parseJSON(data);
          $.each(obj.data, function(key, value) {
            return $("#modal-clientes .modal-body tbody").append("<tr class='list-cli-row' data-cid='" + key + "'><td>" + key + "</td><td>" + value.nombre + "</td><td>" + value.direccion + "</td></tr>");
          });
          return $("#modal-clientes").modal('show');
        },
        type: 'POST',
        url: "ajax.php"
      });
      return null;
    };
  })(jQuery);

}).call(this);
