// Generated by CoffeeScript 1.8.0
(function() {
  (function($) {
    var addArticulo, clearForm, deleteRow, getArticulo, getCliente, getClientes, setCantidad;
    $("#cod-cliente").on("blur", function() {
      return getCliente($(this));
    });
    '$( window ).on( "beforeunload", () ->\n	return "Todos los datos actuales se perderan si continúa." \n)';
    $("#search-clientes").on("click", function() {
      return getClientes();
    });
    $("body").on("click", ".list-cli-row", function() {
      $("#cod-cliente").val($(this).data("cid"));
      $("#modal-clientes").modal('hide');
      return $("#cod-cliente").blur();
    });
    $("body").on("click", ".delete-row", function() {
      return deleteRow($(this));
    });
    $("#articulo-codigo").on("blur", function() {
      return getArticulo($(this));
    });
    $("#articulo-cantidad").on("keyup", function(e) {
      return setCantidad($(this), e);
    });
    $("#articulo-cantidad").on("keydown", function(e) {
      return addArticulo(e);
    });
    $("#clear-form").on("click", function() {
      return clearForm();
    });
    getCliente = function(elm) {
      var data, val;
      val = elm.val();
      data = {
        'accion': "obtener-cliente",
        'data': {}
      };
      data.data['cliente-id'] = val;
      if (val !== '') {
        $.ajax({
          beforeSend: function(xhr, settings) {
            return null;
          },
          complete: function(xhr, status) {
            return null;
          },
          data: '&json=' + JSON.stringify(data),
          success: function(data, status, xhr) {
            var obj;
            obj = $.parseJSON(data);
            if (obj.estado === "exito") {
              return $("#datos-cliente").html("" + obj.data.nombre + "<br><small>" + obj.data.direccion + "</small>");
            }
          },
          type: 'POST',
          url: "ajax.php"
        });
        return null;
      }
    };
    getClientes = function() {
      var data;
      data = {
        'accion': "obtener-clientes",
        'data': {}
      };
      $.ajax({
        beforeSend: function(xhr, settings) {
          return null;
        },
        complete: function(xhr, status) {
          return null;
        },
        data: '&json=' + JSON.stringify(data),
        success: function(data, status, xhr) {
          var obj;
          obj = $.parseJSON(data);
          $.each(obj.data, function(key, value) {
            return $("#modal-clientes .modal-body tbody").append("<tr class='list-cli-row' data-cid='" + key + "'><td>" + key + "</td><td>" + value.nombre + "</td><td>" + value.direccion + "</td></tr>");
          });
          return $("#modal-clientes").modal('show');
        },
        type: 'POST',
        url: "ajax.php"
      });
      return null;
    };
    getArticulo = function(elm) {
      var data, val;
      val = elm.val();
      data = {
        'accion': "obtener-articulo",
        'data': {}
      };
      data.data['articulo-id'] = val;
      if (val !== '') {
        $.ajax({
          beforeSend: function(xhr, settings) {
            return null;
          },
          complete: function(xhr, status) {
            return null;
          },
          data: '&json=' + JSON.stringify(data),
          success: function(data, status, xhr) {
            var obj;
            obj = $.parseJSON(data);
            if (obj.estado === "exito") {
              $("#articulo-denominacion").html("" + obj.data.denominacion);
              $("#articulo-precio").html("$ " + obj.data.precio);
              return $("#articulo-importe").html("$ " + obj.data.precio);
            }
          },
          type: 'POST',
          url: "ajax.php"
        });
        return null;
      }
    };
    setCantidad = function(cantidad, evt) {
      var importe;
      if ($("#articulo-codigo").val() !== "") {
        cantidad = cantidad.val();
        if (cantidad === "") {
          cantidad = "0";
        }
        importe = parseFloat(cantidad) * parseFloat($("#articulo-precio").html().replace("$ ", ""));
        $("#articulo-importe").html("$ " + importe);
      }
      return null;
    };
    addArticulo = function(evt) {
      if (evt.keyCode === 9 || evt.keyCode === 13) {
        if ($("#articulo-codigo").val() !== "") {
          if ($("#articulo-cantidad").val() === "") {
            $("#articulo-cantidad").val("1");
          }
          $(".articulos tbody").append("<tr> <td>" + ($("#articulo-codigo").val()) + "</td> <td class='text-center'>" + ($("#articulo-cantidad").val()) + "</td> <td>" + ($("#articulo-denominacion").html()) + "</td> <td class='text-right'>" + ($("#articulo-precio").html()) + "</td> <td class='text-right'>" + ($("#articulo-importe").html()) + "</td> <td class='text-right'><a class='btn btn-danger delete-row' href='#'><i class='fa fa-trash'></i></a></td> </tr>");
          evt.preventDefault();
          return clearForm();
        }
      }
    };
    clearForm = function() {
      $("#articulo-codigo").val("");
      $("#articulo-cantidad").val("");
      $("#articulo-denominacion").html("");
      $("#articulo-precio").html("$ 0.00");
      $("#articulo-importe").html("$ 0.00");
      return $("#articulo-codigo").focus();
    };
    return deleteRow = function(elm) {
      elm.parents("tr").remove();
      return clearForm();
    };
  })(jQuery);

}).call(this);
