// Generated by CoffeeScript 1.8.0
(function() {
  (function($) {
    var actualizaTotales, addArticulo, cambiarLista, clearForm, deleteRow, getArticulo, getCliente, getClientes, setCantidad;
    numeral.language('es', {
      delimiters: {
        thousands: '.',
        decimal: ','
      },
      currency: {
        symbol: '$'
      }
    });
    numeral.language('es');
    $("#cod-cliente").on("blur", function() {
      return getCliente($(this));
    });
    '$( window ).on( "beforeunload", () ->\n	return "Todos los datos actuales se perderan si continúa." \n)';
    $("#search-clientes").on("click", function(e) {
      e.preventDefault();
      return getClientes();
    });
    $("body").on("click", ".list-cli-row", function(e) {
      e.preventDefault();
      $("#cod-cliente").val($(this).data("cid"));
      $("#modal-clientes").modal('hide');
      return $("#cod-cliente").blur();
    });
    $("body").on("click", ".delete-row", function(e) {
      e.preventDefault();
      return deleteRow($(this));
    });
    $("#articulo-codigo").on("blur", function() {
      return getArticulo($(this));
    });
    $("#articulo-cantidad").on("keyup", function(e) {
      return setCantidad($(this), e);
    });
    $("#articulo-cantidad").on("keydown", function(e) {
      return addArticulo(e);
    });
    $("#clear-form").on("click", function(e) {
      e.preventDefault();
      return clearForm();
    });
    $(".cambiar-listas label").on("click", function(e) {
      e.preventDefault();
      return cambiarLista(e);
    });
    getCliente = function(elm) {
      var data, val;
      val = elm.val();
      data = {
        'accion': "obtener-cliente",
        'data': {}
      };
      data.data['cliente-id'] = val;
      if (val !== '') {
        $.ajax({
          beforeSend: function(xhr, settings) {
            return null;
          },
          complete: function(xhr, status) {
            return null;
          },
          data: '&json=' + JSON.stringify(data),
          success: function(data, status, xhr) {
            var obj;
            obj = $.parseJSON(data);
            if (obj.estado === "exito") {
              return $("#datos-cliente").html("" + obj.data.nombre + "<br> <small>" + obj.data.direccion + "</small>");
            }
          },
          type: 'POST',
          url: "ajax.php"
        });
        return null;
      }
    };
    getClientes = function() {
      var data;
      data = {
        'accion': "obtener-clientes",
        'data': {}
      };
      $.ajax({
        beforeSend: function(xhr, settings) {
          return null;
        },
        complete: function(xhr, status) {
          return null;
        },
        data: '&json=' + JSON.stringify(data),
        success: function(data, status, xhr) {
          var obj;
          obj = $.parseJSON(data);
          $.each(obj.data, function(key, value) {
            return $("#modal-clientes .modal-body tbody").append("<tr class='list-cli-row' data-cid='" + key + "'> <td>" + key + "</td> <td>" + value.nombre + "</td> <td>" + value.direccion + "</td> </tr>");
          });
          return $("#modal-clientes").modal('show');
        },
        type: 'POST',
        url: "ajax.php"
      });
      return null;
    };
    getArticulo = function(elm) {
      var data, val;
      val = elm.val();
      data = {
        'accion': "obtener-articulo",
        'data': {}
      };
      data.data['articulo-id'] = val;
      if (val !== '') {
        $.ajax({
          beforeSend: function(xhr, settings) {
            return null;
          },
          complete: function(xhr, status) {
            return null;
          },
          data: '&json=' + JSON.stringify(data),
          success: function(data, status, xhr) {
            var obj, precio1, precio2, precio3, precioFormat;
            obj = $.parseJSON(data);
            precio1 = obj.data.precio.lista1;
            precio2 = obj.data.precio.lista2;
            precio3 = obj.data.precio.lista3;
            if ($("#lista1").parent().hasClass("active")) {
              precioFormat = numeral(precio1).format("$ 0,0.00");
            } else if ($("#lista2").parent().hasClass("active")) {
              precioFormat = numeral(precio2).format("$ 0,0.00");
            } else if ($("#lista3").parent().hasClass("active")) {
              precioFormat = numeral(precio3).format("$ 0,0.00");
            }
            if (obj.estado === "exito") {
              $("#articulo-denominacion").html("" + obj.data.denominacion);
              $("#articulo-precio").html("" + precioFormat);
              $("#articulo-precio").data("precio1", "" + precio1);
              $("#articulo-precio").data("precio2", "" + precio2);
              $("#articulo-precio").data("precio3", "" + precio3);
              return $("#articulo-importe").html("" + precioFormat);
            }
          },
          type: 'POST',
          url: "ajax.php"
        });
        return null;
      }
    };
    setCantidad = function(cantidad, evt) {
      var cant, importe, importeFormat, precio;
      if ($("#articulo-codigo").val() !== "") {
        cantidad = cantidad.val();
        if (cantidad === "") {
          cantidad = "1";
        }
        cant = parseFloat(cantidad);
        if ($("#lista1").parent().hasClass("active")) {
          precio = parseFloat($("#articulo-precio").data("precio1"));
        } else if ($("#lista2").parent().hasClass("active")) {
          precio = parseFloat($("#articulo-precio").data("precio2"));
        } else if ($("#lista3").parent().hasClass("active")) {
          precio = parseFloat($("#articulo-precio").data("precio3"));
        }
        importe = cant * precio;
        importeFormat = numeral(importe).format("$ 0,0.00");
        $("#articulo-importe").data("value", "" + importe);
        $("#articulo-importe").html("" + importeFormat);
      }
      return null;
    };
    addArticulo = function(evt) {
      var cantidad, codigo, denominacion, importe, importeFormat, precio1, precio2, precio3, precioFormat;
      if (evt.keyCode === 9 || evt.keyCode === 13) {
        codigo = $("#articulo-codigo").val();
        cantidad = $("#articulo-cantidad").val();
        denominacion = $("#articulo-denominacion").html();
        precio1 = $("#articulo-precio").data("precio1");
        precio2 = $("#articulo-precio").data("precio2");
        precio3 = $("#articulo-precio").data("precio3");
        precioFormat = $("#articulo-precio").html();
        importe = $("#articulo-importe").data("value");
        importeFormat = $("#articulo-importe").html();
        if (codigo !== "") {
          if (cantidad === "") {
            $("#articulo-cantidad").val("1");
            cantidad = "1";
          }
          $(".articulos tbody").append("<tr> <td>" + codigo + "</td> <td class='text-center cantidad' data-value='" + cantidad + "' >" + cantidad + "</td> <td>" + denominacion + "</td> <td class='text-right precio' data-precio1='" + precio1 + "' data-precio2='" + precio2 + "' data-precio3='" + precio3 + "' > " + precioFormat + " </td> <td class='text-right importe' data-value='" + importe + "' > " + importeFormat + " </td> <td class='text-right'> <a class='btn btn-danger delete-row' href='#'> <i class='fa fa-trash'></i> </a> </td> </tr>");
          evt.preventDefault();
          actualizaTotales();
          return clearForm();
        }
      }
    };
    clearForm = function() {
      $("#articulo-codigo").val("");
      $("#articulo-cantidad").val("");
      $("#articulo-denominacion").html("");
      $("#articulo-precio").html("$ 0.00");
      $("#articulo-importe").html("$ 0.00");
      return $("#articulo-codigo").focus();
    };
    deleteRow = function(elm) {
      elm.parents("tr").remove();
      actualizaTotales();
      return clearForm();
    };
    actualizaTotales = function() {
      var total, totalFormat;
      total = 0;
      $(".articulos tbody tr").each(function(i) {
        return total += parseFloat($(this).find("td.importe").data("value"));
      });
      totalFormat = numeral(total).format("$ 0,0.00");
      $("#total").html(totalFormat);
      return $("#contar").html($(".articulos tbody tr").length);
    };
    return cambiarLista = function(evt) {
      var lista;
      lista = $(evt.target).find('input').attr('id').replace("lista", "precio");
      $(".articulos tbody tr").each(function(i) {
        var cantidad, importe, importeFormat, precio, precioFormat;
        cantidad = $(this).find(".cantidad").data("value");
        precio = $(this).find(".precio").data(lista);
        precioFormat = numeral(precio).format("$ 0,0.00");
        importe = cantidad * precio;
        importeFormat = numeral(importe).format("$ 0,0.00");
        $(this).find(".precio").html("" + precioFormat);
        $(this).find(".importe").data("value", "" + importe);
        return $(this).find(".importe").html("" + importeFormat);
      });
      return actualizaTotales();
    };
  })(jQuery);

}).call(this);
